export const SET_EVENTS = 'content/SET_EVENTS'
export const SET_EVENTS_LOADING = 'content/SET_EVENTS_LOADING'
export const SET_EVENTS_ERROR = 'content/SET_EVENTS_ERROR'

export const SET_EVENT_CONCEPTS = 'content/SET_EVENT_CONCEPTS'
export const SET_EVENT_CONCEPTS_LOADING = 'content/SET_EVENT_CONCEPTS_LOADING'
export const SET_EVENT_CONCEPTS_ERROR = 'content/SET_EVENT_CONCEPTS_ERROR'

export const SET_TEAM_MEMBERS = 'content/SET_TEAM_MEMBERS'
export const SET_TEAM_MEMBERS_LOADING = 'content/SET_TEAM_MEMBERS_LOADING'
export const SET_TEAM_MEMBERS_ERROR = 'content/SET_TEAM_MEMBERS_ERROR'

export const SET_TESTIMONIALS = 'content/SET_TESTIMONIALS'
export const SET_TESTIMONIALS_LOADING = 'content/SET_TESTIMONIALS_LOADING'
export const SET_TESTIMONIALS_ERROR = 'content/SET_TESTIMONIALS_ERROR'

export const SET_SOCIAL_MEDIAS = 'content/SET_SOCIAL_MEDIAS'
export const SET_SOCIAL_MEDIAS_LOADING = 'content/SET_SOCIAL_MEDIAS_LOADING'
export const SET_SOCIAL_MEDIAS_ERROR = 'content/SET_SOCIAL_MEDIAS_ERROR'