export const SET_EVENTS = 'content/SET_EVENTS'
export const SET_EVENTS_LOADING = 'content/SET_EVENTS_LOADING'
export const SET_EVENTS_ERROR = 'content/SET_EVENTS_ERROR'

export const SET_EVENT_CONCEPTS = 'content/SET_EVENT_CONCEPTS'
export const SET_EVENT_CONCEPTS_LOADING = 'content/SET_EVENT_CONCEPTS_LOADING'
export const SET_EVENT_CONCEPTS_ERROR = 'content/SET_EVENT_CONCEPTS_ERROR'