export const SET_STATIC_CONTENT = 'staticcontent/SET_STATIC_CONTENT'
export const SET_STATIC_CONTENT_LOADING = 'staticcontent/SET_STATIC_CONTENT_LOADING'
export const SET_STATIC_CONTENT_ERROR = 'staticcontent/SET_STATIC_CONTENT_ERROR'